### ISSUE TITLE
website styling: FIIND header text is wider than column width

### ISSUE THREAD

**Issue by rbakker** [neuroanatomy/fiind#2]
On the FIIND website main page, the word FIIND and text 'Ferret Interactive ...', encoded as an image, is wider than the column width and therefore the words are truncated.
![fiind-website-styling](https://user-images.githubusercontent.com/1036031/71275446-b6d72700-2354-11ea-9a83-070ad1845a70.jpg)

**Comment by katjaq** [comment]
Hey Rembrandt! Thank you for pointing this out! I will look into it! Funny you get a completely different font!

**Comment by katjaq** [comment]
hello! I pushed a fix – as I cannot reproduce the error, could you please check and let me know if it displays alright now? :) many thanks. 
I know it's holidays – i don't expect immediate action ;)

**Comment by rbakker** [comment]
It now looks as attached and that looks good to me. Please note: the blue rectangle is shown because I did a 'select all' to show object margins.
![fiind_styling_issue2](https://user-images.githubusercontent.com/1036031/71313465-769da480-2439-11ea-87be-5b111af2da58.png)

**Comment by katjaq** [comment]
Fantastic! :) 
thank you very much again! :) 👍
