### ISSUE TITLE
Add a "partners" section with project partners before funding

### ISSUE THREAD

**Issue by r03ert0** [neuroanatomy/fiind#4]
Groupe de neuroanatomie appliquée et théorique, Institut Pasteur, France (Roberto Toro)
Neuroinformatics research group, Radboud University Nijmegen, The Netherlands (Paul Tiesinga).
MIRCen, Commisariat aux Énergies Alternatives, France (Thierry Delzescaux)
McGill Centre for Integrative Neuroscience, Quebec, Canada (Alan Evans)

**Comment by katjaq** [comment]
Thanks! Done in push 4c03f4c commit 7c5d3e670aaceef263d7a5a48877279d34ac2de8
